@echo off
set "ASPNETCORE_ENVIRONMENT=Development"
set "ConnectionStrings__DefaultConnection=Server=medrecpro-test-sentinel.invalid;Database=MedRecProTest;User Id=test;Password=test;TrustServerCertificate=True;Connect Timeout=1"
set "DefaultConnection=Server=medrecpro-test-sentinel.invalid;Database=MedRecProTest;User Id=test;Password=test;TrustServerCertificate=True;Connect Timeout=1"
set "Dev__DB__Connection=Server=medrecpro-test-sentinel.invalid;Database=MedRecProTest;User Id=test;Password=test;TrustServerCertificate=True;Connect Timeout=1"
set "Security__DB__PKSecret=MedRecPro-Test-Only-PK-Secret"
set "KeyVaultUrl="
set "McpServer__Url="
set "McpServer__JwtSigningKey="
set "FeatureFlags__BackgroundProcessingEnabled=false"
set "FeatureFlags__ActivityTrackingEnabled=false"
set "DatabaseUsageMonitor__Enabled=false"
set "DatabaseKeepAlive__Enabled=false"
set "Logging__EventLog__LogLevel__Default=None"
cd /d "C:\Users\chris\OneDrive\Documents\Repos"
dotnet "C:\Users\chris\OneDrive\Documents\Repos\MedRecPro\bin\Debug\net8.0\MedRecPro.dll" --urls http://127.0.0.1:5093 1> "C:\Users\chris\OneDrive\Documents\Repos\.codex-build\swagger-ui-server\stdout.log" 2> "C:\Users\chris\OneDrive\Documents\Repos\.codex-build\swagger-ui-server\stderr.log"
