using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MedRecPro.Models
{
    /**************************************************************/
    /// <summary>
    /// Represents a dashboard product favorite saved by an authenticated application user.
    /// </summary>
    /// <remarks>
    /// Favorites are scoped to the ASP.NET Core Identity user and the SPL
    /// <see cref="DocumentGUID"/> used by AE dashboard product summaries. The table does
    /// not enforce a foreign key to SPL documents because dashboard projections can be
    /// rebuilt independently of user preferences.
    /// </remarks>
    /// <example>
    /// <code>
    /// var favorite = new AspNetUserFavorite
    /// {
    ///     UserId = 42,
    ///     DocumentGUID = documentGuid,
    ///     CreatedAt = DateTime.UtcNow
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="User"/>
    /// <seealso cref="LabelView.AeDrugSummary"/>
    [Table("AspNetUserFavorite")]
    public class AspNetUserFavorite
    {
        #region properties

        /**************************************************************/
        /// <summary>
        /// Gets or sets the unique favorite row identifier.
        /// </summary>
        /// <remarks>
        /// This value is generated by the database and is not exposed through the AE
        /// dashboard DTO contract.
        /// </remarks>
        /// <seealso cref="AspNetUserFavorite"/>
        [Key]
        public long AspNetUserFavoriteID { get; set; }

        /**************************************************************/
        /// <summary>
        /// Gets or sets the ASP.NET Core Identity user identifier that owns the favorite.
        /// </summary>
        /// <remarks>
        /// The value references the Identity primary key on <see cref="User"/> and is resolved server-side from
        /// the authenticated user, never from client-provided dashboard payloads.
        /// </remarks>
        /// <seealso cref="User"/>
        public long UserId { get; set; }

        /**************************************************************/
        /// <summary>
        /// Gets or sets the SPL document identifier for the favorited dashboard product.
        /// </summary>
        /// <remarks>
        /// The AE dashboard uses raw document GUIDs as stable product keys to match
        /// existing label endpoint conventions.
        /// </remarks>
        /// <seealso cref="LabelView.AeDrugSummary.DocumentGUID"/>
        public Guid DocumentGUID { get; set; }

        /**************************************************************/
        /// <summary>
        /// Gets or sets the UTC timestamp when the favorite was first created.
        /// </summary>
        /// <remarks>
        /// Favorite list ordering uses this value for the default
        /// CreatedAt-descending picker behavior.
        /// </remarks>
        /// <seealso cref="AspNetUserFavorite.UpdatedAt"/>
        public DateTime CreatedAt { get; set; }

        /**************************************************************/
        /// <summary>
        /// Gets or sets the UTC timestamp when the favorite row was last updated.
        /// </summary>
        /// <remarks>
        /// The current dashboard delete mode is hard-delete, so this value is reserved
        /// for forward-compatible favorite metadata updates.
        /// </remarks>
        /// <seealso cref="AspNetUserFavorite.CreatedAt"/>
        public DateTime? UpdatedAt { get; set; }

        /**************************************************************/
        /// <summary>
        /// Gets or sets the user navigation property for the favorite owner.
        /// </summary>
        /// <remarks>
        /// EF Core maps this relationship to <see cref="UserId"/> with cascade delete
        /// so deleted users do not leave orphaned dashboard favorites.
        /// </remarks>
        /// <seealso cref="User"/>
        [ForeignKey("UserId")]
        public User? User { get; set; }

        #endregion properties
    }
}
