using System.ComponentModel.DataAnnotations;

namespace MedRecPro.Models
{
    #region comparison request models

    // Enhanced model classes for MedRecPro AI comparison integration
    /// <summary>
    /// Represents a request to generate a comparison report between SPL XML and JSON representations.
    /// This model is used to initiate the AI-powered analysis of label data completeness.
    /// </summary>
    /// <remarks>
    /// The comparison process validates that all data from the original SPL XML file 
    /// has been accurately represented in the corresponding JSON format.
    /// </remarks>
    /// <example>
    /// <code>
    /// var request = new ComparisonRequest 
    /// {
    ///     FileId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    ///     AdditionalInstructions = "Focus on clinical trial data and drug interaction completeness"
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="ComparisonResponse"/>
    /// <seealso cref="ComparisonResult"/>
    public class ComparisonRequest
    {
        #region implementation

        /// <summary>
        /// Gets or sets the unique identifier for the uploaded SPL file to be compared.
        /// This identifier is generated during the file upload process and used to retrieve
        /// both XML and JSON representations for comparison.
        /// </summary>
        /// <seealso cref="ComparisonResponse.FileId"/>
        [Required]
        public string FileId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets optional additional instructions for the AI comparison analysis.
        /// These instructions can specify particular areas of focus or special requirements
        /// for the comparison process.
        /// </summary>
        /// <remarks>
        /// Common instructions include focusing on specific sections like clinical trials,
        /// drug interactions, dosage information, or contraindications.
        /// </remarks>
        /// <example>
        /// Examples: "Focus on safety data completeness", "Emphasize drug interaction analysis"
        /// </example>
        public string? AdditionalInstructions { get; set; }

        #endregion
    }

    #endregion

    #region comparison response models

    // Enhanced model classes for MedRecPro AI comparison integration
    /// <summary>
    /// Represents the response from a comparison analysis operation, containing the file information
    /// and detailed comparison results generated by the AI system.
    /// </summary>
    /// <remarks>
    /// This response provides comprehensive information about the comparison between SPL XML
    /// and JSON representations, including completeness metrics and identified issues.
    /// </remarks>
    /// <example>
    /// <code>
    /// var response = new ComparisonResponse
    /// {
    ///     FileId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    ///     FileName = "sample-spl.xml",
    ///     Result = new ComparisonResult { IsComplete = true },
    ///     GeneratedAt = DateTime.UtcNow
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="ComparisonRequest"/>
    /// <seealso cref="ComparisonResult"/>
    public class ComparisonResponse
    {
        #region implementation

        /// <summary>
        /// Gets or sets the unique identifier of the compared file, matching the original request.
        /// This provides traceability between the request and response.
        /// </summary>
        /// <seealso cref="ComparisonRequest.FileId"/>
        public string FileId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the original name of the uploaded SPL file that was analyzed.
        /// This helps users identify which file the comparison results refer to.
        /// </summary>
        public string FileName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the detailed comparison analysis results generated by the AI system.
        /// Contains all findings, metrics, and identified issues from the comparison process.
        /// </summary>
        /// <seealso cref="ComparisonResult"/>
        public ComparisonResult Result { get; set; } = new();

        /// <summary>
        /// Gets or sets the UTC timestamp when the comparison analysis was completed.
        /// This provides audit trail information for the comparison operation.
        /// </summary>
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        #endregion
    }

    #endregion

    #region comparison result models

    // Enhanced model classes for MedRecPro AI comparison integration
    /// <summary>
    /// Contains the detailed results of the AI comparison analysis between SPL XML and JSON formats.
    /// Provides comprehensive information about data completeness, identified issues, and metrics.
    /// </summary>
    /// <remarks>
    /// The comparison result represents the AI's assessment of whether all data from the original
    /// SPL XML has been accurately preserved in the JSON representation, along with detailed
    /// analysis and quantitative metrics.
    /// </remarks>
    /// <example>
    /// <code>
    /// var result = new ComparisonResult
    /// {
    ///     IsComplete = true,
    ///     Summary = "✅ COMPLETE DATA REPRESENTATION - All data from XML is present in JSON",
    ///     DetailedAnalysis = "Systematic comparison shows...",
    ///     Issues = new List&lt;ComparisonIssue&gt;(),
    ///     Metrics = new ComparisonMetrics { CompletionPercentage = 100.0 }
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="ComparisonResponse"/>
    /// <seealso cref="ComparisonIssue"/>
    /// <seealso cref="ComparisonMetrics"/>
    public class ComparisonResult
    {
        #region implementation

        /// <summary>
        /// Gets or sets a value indicating whether the JSON representation contains all data
        /// from the original SPL XML file. True indicates complete data preservation.
        /// </summary>
        /// <seealso cref="ComparisonMetrics.CompletionPercentage"/>
        public bool IsComplete { get; set; }

        /// <summary>
        /// Gets or sets a concise summary of the comparison results, typically including
        /// an overall assessment and key findings from the AI analysis.
        /// </summary>
        /// <remarks>
        /// Summary often starts with ✅ for complete data or ❌ for incomplete data,
        /// followed by a brief explanation of the findings.
        /// </remarks>
        public string Summary { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the comprehensive detailed analysis provided by the AI system,
        /// including methodology, findings, and reasoning behind the comparison results.
        /// </summary>
        /// <remarks>
        /// Contains the full AI-generated analysis explaining how the comparison was performed,
        /// what sections were examined, and detailed findings for each area.
        /// </remarks>
        public string DetailedAnalysis { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the list of specific issues identified during the comparison process.
        /// Empty list indicates no issues were found.
        /// </summary>
        /// <seealso cref="ComparisonIssue"/>
        public List<ComparisonIssue> Issues { get; set; } = new();

        /// <summary>
        /// Gets or sets the quantitative metrics calculated during the comparison analysis,
        /// providing measurable data about the completeness assessment.
        /// </summary>
        /// <seealso cref="ComparisonMetrics"/>
        public ComparisonMetrics Metrics { get; set; } = new();

        #endregion
    }

    #endregion

    #region comparison issue models

    // Enhanced model classes for MedRecPro AI comparison integration
    /// <summary>
    /// Represents a specific issue or discrepancy identified during the comparison analysis
    /// between SPL XML and JSON representations.
    /// </summary>
    /// <remarks>
    /// Issues can range from missing data sections to mismatched values or structural
    /// differences between the XML and JSON formats. Each issue includes contextual
    /// information to help users understand and address the problem.
    /// </remarks>
    /// <example>
    /// <code>
    /// var issue = new ComparisonIssue
    /// {
    ///     Type = "Missing",
    ///     Section = "Drug Interactions",
    ///     Description = "Drug interaction section present in XML but missing in JSON",
    ///     Severity = "High"
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="ComparisonResult.Issues"/>
    public class ComparisonIssue
    {
        #region implementation

        /// <summary>
        /// Gets or sets the type classification of the identified issue.
        /// Common types include "Missing", "Mismatch", and "Warning".
        /// </summary>
        /// <remarks>
        /// - "Missing": Data present in XML but absent in JSON
        /// - "Mismatch": Data differs between XML and JSON representations
        /// - "Warning": Potential concerns that may require attention
        /// </remarks>
        public string Type { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the specific section or area of the SPL document where the issue was found.
        /// This helps users locate and address the identified problem.
        /// </summary>
        /// <example>
        /// Examples: "Drug Interactions", "Dosage and Administration", "Clinical Pharmacology"
        /// </example>
        public string Section { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets a detailed description of the identified issue, explaining what
        /// was found and why it represents a problem in the data comparison.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the severity level of the issue, indicating its importance
        /// and priority for resolution. Values include "High", "Medium", and "Low".
        /// </summary>
        /// <remarks>
        /// - "High": Critical issues affecting data integrity or safety information
        /// - "Medium": Important issues that should be addressed but aren't critical
        /// - "Low": Minor issues or formatting differences
        /// </remarks>
        public string Severity { get; set; } = string.Empty;

        #endregion
    }

    #endregion

    #region comparison metrics models

    // Enhanced model classes for MedRecPro AI comparison integration
    /// <summary>
    /// Provides quantitative metrics about the comparison analysis results,
    /// offering measurable data about the completeness and quality of data preservation.
    /// </summary>
    /// <remarks>
    /// These metrics provide objective measurements that complement the qualitative
    /// analysis, helping users understand the extent of data preservation between
    /// SPL XML and JSON formats.
    /// </remarks>
    /// <example>
    /// <code>
    /// var metrics = new ComparisonMetrics
    /// {
    ///     TotalSections = 25,
    ///     CompleteSections = 23,
    ///     MissingSections = 2,
    ///     CompletionPercentage = 92.0
    /// };
    /// </code>
    /// </example>
    /// <seealso cref="ComparisonResult.Metrics"/>
    /// <seealso cref="ComparisonResult.IsComplete"/>
    public class ComparisonMetrics
    {
        #region implementation

        /// <summary>
        /// Gets or sets the total number of sections identified in the original SPL XML document.
        /// This represents the baseline count for comparison analysis.
        /// </summary>
        /// <seealso cref="CompleteSections"/>
        /// <seealso cref="MissingSections"/>
        public int TotalSections { get; set; }

        /// <summary>
        /// Gets or sets the number of sections that were successfully preserved in the JSON
        /// representation with complete and accurate data.
        /// </summary>
        /// <seealso cref="TotalSections"/>
        /// <seealso cref="CompletionPercentage"/>
        public int CompleteSections { get; set; }

        /// <summary>
        /// Gets or sets the number of sections from the XML that are missing or incomplete
        /// in the JSON representation.
        /// </summary>
        /// <remarks>
        /// This value should equal TotalSections minus CompleteSections and represents
        /// areas requiring attention to achieve complete data preservation.
        /// </remarks>
        /// <seealso cref="TotalSections"/>
        /// <seealso cref="CompleteSections"/>
        public int MissingSections { get; set; }

        /// <summary>
        /// Gets or sets the calculated percentage of data completeness, representing
        /// the ratio of complete sections to total sections multiplied by 100.
        /// </summary>
        /// <remarks>
        /// A value of 100.0 indicates perfect data preservation, while lower values
        /// indicate areas where data may be missing or incomplete in the JSON format.
        /// </remarks>
        /// <seealso cref="CompleteSections"/>
        /// <seealso cref="TotalSections"/>
        public double CompletionPercentage { get; set; }

        #endregion
    }

    #endregion
}